/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.di_p4;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author USER
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    
    private static final String NOMBRE_ARCHIVO = "puntuaciones.txt";
    
    public void cargarPuntuacionesEnLista() {
        
        DefaultListModel<String> model = new DefaultListModel<>();
        File archivoPuntuaciones = new File(NOMBRE_ARCHIVO);
        
        if (!archivoPuntuaciones.exists()) {
            model.addElement("No hay puntuaciones registradas.");
            jList1.setModel(model);
            return;
        }

        try (BufferedReader reader = new BufferedReader(new FileReader(archivoPuntuaciones))) {
            String linea;
            
            while ((linea = reader.readLine()) != null) {
                model.addElement(linea);
            }
        } catch (IOException e) {
            model.addElement("ERROR al cargar el archivo.");
            System.err.println("Error al leer el archivo: " + e.getMessage());
        }
        
        jList1.setModel(model);
    }
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        cargarPuntuacionesEnLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jBstart = new javax.swing.JButton();
        jBexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("JUEGO DVD");
        getContentPane().add(jLabel1, new java.awt.GridBagConstraints());

        jBstart.setBackground(new java.awt.Color(51, 51, 255));
        jBstart.setForeground(new java.awt.Color(255, 255, 255));
        jBstart.setText("Empezar");
        jBstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBstartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jBstart, gridBagConstraints);

        jBexit.setBackground(new java.awt.Color(153, 153, 153));
        jBexit.setText("Salir");
        jBexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(jBexit, gridBagConstraints);

        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBexitActionPerformed

    private void jBstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBstartActionPerformed
        //Desvisibilizo esta pestaña
        this.setVisible(false);        

        //Visibilizo el juego
        Ventana v = new Ventana();
        v.setVisible(true);
        
        
    }//GEN-LAST:event_jBstartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBexit;
    private javax.swing.JButton jBstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
