/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.di_p4;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class PantallaFinal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaFinal.class.getName());

    private ObjetoAlmacen oa = new ObjetoAlmacen();
    
    /**
     * Creates new form PantallaFinal
     */
    
    public PantallaFinal(int puntuacion) {
        initComponents();

        this.oa.setPuntuacion(puntuacion); 

        jLfyp.setText("Felicidades, has hecho: "+ this.oa.getPuntuacion() +" puntos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jBnombre = new javax.swing.JLabel();
        jBguardar = new javax.swing.JButton();
        jLfyp = new javax.swing.JLabel();
        jTFnombre = new javax.swing.JTextField();
        jBsalir = new javax.swing.JButton();
        jLfyp1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jBnombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBnombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jBnombre, gridBagConstraints);

        jBguardar.setBackground(new java.awt.Color(0, 153, 0));
        jBguardar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBguardar.setText("GUARDAR");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(jBguardar, gridBagConstraints);

        jLfyp.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLfyp.setText("//Felicidades y puntos//");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLfyp, gridBagConstraints);

        jTFnombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jTFnombre, gridBagConstraints);

        jBsalir.setBackground(new java.awt.Color(102, 0, 0));
        jBsalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBsalir.setForeground(new java.awt.Color(255, 255, 255));
        jBsalir.setText("NO GUARDAR");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(jBsalir, gridBagConstraints);

        jLfyp1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLfyp1.setText("Introduce tu nombre y guarda la puntuación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLfyp1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        String nombre = jTFnombre.getText();
        
        // 3. Establece el nombre en el objeto 'oa' de la clase, que ya tiene la puntuación
        this.oa.setNombre(nombre); 
        
        if(!nombre.trim().isEmpty()){ // Usa trim().isEmpty() para evitar solo espacios
            boolean proceso = this.oa.guardarPuntuacion();
            
            if (proceso){
                JOptionPane.showMessageDialog(this, "Datos guardados en puntuaciones.txt", "Puntoacion guardada correctamente", JOptionPane.PLAIN_MESSAGE);

                Menu m = new Menu();
                m.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debes de introducir tu nombre", "Faltan campos", JOptionPane.WARNING_MESSAGE);
            return;
        } 
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBguardar;
    private javax.swing.JLabel jBnombre;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLfyp;
    private javax.swing.JLabel jLfyp1;
    private javax.swing.JTextField jTFnombre;
    // End of variables declaration//GEN-END:variables
}
