/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.di_p4;

import java.util.Set;
import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    private boolean pause = false;
    private int puntuacion = 0;
    
    private static final int velocidadBase = 1; // La velocidad mínima a la que se moverá.
    private static final int velocidadMaxima = 25; // Límite para que no sea incontrolable.
    private int dirX = 1; // Dirección horizontal: 1 (derecha), -1 (izquierda)
    private int dirY = 1; // Dirección vertical: 1 (abajo), -1 (arriba)
    private final int RETRASO = 20; // 20ms para un movimiento suave
    
    private javax.swing.Timer timer = null;
    private javax.swing.Timer timerVisible = null;
    private Integer segundos= 0;
    
    private int altoImagen = 80;
    private int anchoImagen = 80;
        
    /**
     * Creates new form Ventana
     */
    public Ventana() {
    
        //initComponents();
        components(); 
        
        getContentPane().setLayout(null); 
        ImageIcon iconoDVD = ImagenLocal.cargarYRedimensionarIcono("dvdlogo.png", anchoImagen, altoImagen);
        if (iconoDVD != null) {
            jBclick.setIcon(iconoDVD);
            jBclick.setText(""); 
        } else {
            jBclick.setText("Error DVD: No se encontró la imagen."); 
        }
        jBclick.setBounds(10, 10, anchoImagen, altoImagen);
        getContentPane().add(jBclick); 

        
        timer = new javax.swing.Timer(RETRASO, (java.awt.event.ActionEvent e) -> {
            moverBoton();
        });
        timerVisible = new javax.swing.Timer(1000, (java.awt.event.ActionEvent e) -> {
            segundos++;
            jMtiempo.setText("Tiempo: " +segundos+ "s"); 
            
            if (segundos >= 31){
                timerVisible.stop();
                fin();
            }
        });

        this.setSize(600, 400); 

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    private void components() {

    jBclick = new javax.swing.JButton();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMopc = new javax.swing.JMenu();
    jMIvolver = new javax.swing.JMenuItem();
    jMIsalir = new javax.swing.JMenuItem();
    jMenu1 = new javax.swing.JMenu();
    jMIpausa = new javax.swing.JMenuItem();
    jMpuntuacion = new javax.swing.JMenu();
    jMtiempo = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMaximumSize(new java.awt.Dimension(400, 300));
    setMinimumSize(new java.awt.Dimension(400, 300));

    jBclick.setText("Click me");
    jBclick.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBclickActionPerformed(evt);
        }
    });

    jMopc.setText("Opciones");

    jMIvolver.setText("Volver");
    jMIvolver.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMIvolverActionPerformed(evt);
        }
    });
    jMopc.add(jMIvolver);

    jMIsalir.setText("Salir");
    jMIsalir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMIsalirActionPerformed(evt);
        }
    });
    jMopc.add(jMIsalir);

    jMenuBar1.add(jMopc);

    jMenu1.setText("Pausa");

    jMIpausa.setText("Pausar");
    jMIpausa.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMIpausaActionPerformed(evt);
        }
    });
    jMenu1.add(jMIpausa);

    jMenuBar1.add(jMenu1);

    jMpuntuacion.setText("Puntuación: 0");
    jMenuBar1.add(jMpuntuacion);

    jMtiempo.setText("Tiempo: 0s");
    jMenuBar1.add(jMtiempo);

    setJMenuBar(jMenuBar1);
    
}
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBclick = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMopc = new javax.swing.JMenu();
        jMIvolver = new javax.swing.JMenuItem();
        jMIsalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMIpausa = new javax.swing.JMenuItem();
        jMpuntuacion = new javax.swing.JMenu();
        jMtiempo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));

        jBclick.setText("Click me");
        jBclick.setMaximumSize(new java.awt.Dimension(40, 40));
        jBclick.setMinimumSize(new java.awt.Dimension(40, 40));
        jBclick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclickActionPerformed(evt);
            }
        });

        jMopc.setText("Opciones");

        jMIvolver.setText("Volver");
        jMIvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIvolverActionPerformed(evt);
            }
        });
        jMopc.add(jMIvolver);

        jMIsalir.setText("Salir");
        jMIsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIsalirActionPerformed(evt);
            }
        });
        jMopc.add(jMIsalir);

        jMenuBar1.add(jMopc);

        jMenu1.setText("Pausa");

        jMIpausa.setText("Pausar");
        jMIpausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIpausaActionPerformed(evt);
            }
        });
        jMenu1.add(jMIpausa);

        jMenuBar1.add(jMenu1);

        jMpuntuacion.setText("Puntuación: 0");
        jMenuBar1.add(jMpuntuacion);

        jMtiempo.setText("Tiempo: 0s");
        jMenuBar1.add(jMtiempo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jBclick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jBclick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents




    private void fin(){
        if (timer != null) timer.stop();

        PantallaFinal pf = new PantallaFinal(puntuacion); 
        pf.setVisible(true);
        this.dispose();
        }
    
    private void moverBoton() {
        if (pause) {
            return; 
        }

        int factorAumento = puntuacion / 10;

        //Velocidad actual y límite máximo
        int velocidadDinamica = velocidadBase + factorAumento;
        int velocidadActual = Math.min(velocidadDinamica, velocidadMaxima);

        //Pasos (paso = dirección * velocidad)
        int pasoX = dirX * velocidadActual;
        int pasoY = dirY * velocidadActual;

        //Mover
        int x = jBclick.getX();
        int y = jBclick.getY();
        int nuevoX = x + pasoX;
        int nuevoY = y + pasoY;

        //Colisiones con el borde
        int anchoVentana = getContentPane().getWidth();
        int altoVentana = getContentPane().getHeight();
        int anchoBoton = jBclick.getWidth();
        int altoBoton = jBclick.getHeight();

        
        //Lógica de Rebote (Colisiones)

        // Rebote Horizontal (Ejes X)
        if (nuevoX + anchoBoton > anchoVentana || nuevoX < 0) {
            dirX = -dirX; // Invierte la dirección
            nuevoX = x + dirX * velocidadActual; 
        }

        // Rebote Vertical (Ejes Y)
        if (nuevoY + altoBoton > altoVentana || nuevoY < 0) {
            dirY = -dirY; // Invierte la dirección            
            nuevoY = y + dirY * velocidadActual;
        }

        jBclick.setLocation(nuevoX, nuevoY);
    }
    
    
    
    
    
    
    private void jMIsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMIsalirActionPerformed

    private void jMIvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIvolverActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jMIvolverActionPerformed

    private void jMIpausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIpausaActionPerformed
        if(pause){ //Si esta pausado
            pause = false; //Despausa
            timerVisible.start();
            jMIpausa.setText("Pausar");
        }
        else if (!pause){ //Si NO esta pausado
            pause = true; //Pausa
            timerVisible.stop();
            jMIpausa.setText("Reanudar");
        }
        
    }//GEN-LAST:event_jMIpausaActionPerformed

    private void jBclickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclickActionPerformed
        if(pause){ //Si esta en pausa no funciona
            return;
        }
        if (!timer.isRunning()) { //El timer no empieza hasta el primer click
            timer.start();
            timerVisible.start();
            return;
        }
        
        puntuacion++;
        
        jMpuntuacion.setText("Puntuación: "+puntuacion);
    }//GEN-LAST:event_jBclickActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana().setVisible(true));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBclick;
    private javax.swing.JMenuItem jMIpausa;
    private javax.swing.JMenuItem jMIsalir;
    private javax.swing.JMenuItem jMIvolver;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMopc;
    private javax.swing.JMenu jMpuntuacion;
    private javax.swing.JMenu jMtiempo;
    // End of variables declaration//GEN-END:variables
}
